// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHF9HVsoeyOi39lUFx2lVUAYi41YSdDNM',
    appId: '1:550368483526:web:0d8810d2efde45d5f09fc7',
    messagingSenderId: '550368483526',
    projectId: 'udemy-flutter-bloc-auth',
    authDomain: 'udemy-flutter-bloc-auth.firebaseapp.com',
    storageBucket: 'udemy-flutter-bloc-auth.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeF-R1eVAGoy9LLkXGyZaxXbWWvFRqF14',
    appId: '1:550368483526:android:4dee078722c47a79f09fc7',
    messagingSenderId: '550368483526',
    projectId: 'udemy-flutter-bloc-auth',
    storageBucket: 'udemy-flutter-bloc-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAykQ_dsyBw6kwPqyG0SQSnA-QdPWiMLFI',
    appId: '1:550368483526:ios:0a85084d3f71713af09fc7',
    messagingSenderId: '550368483526',
    projectId: 'udemy-flutter-bloc-auth',
    storageBucket: 'udemy-flutter-bloc-auth.appspot.com',
    iosBundleId: 'com.example.fbAuthBloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAykQ_dsyBw6kwPqyG0SQSnA-QdPWiMLFI',
    appId: '1:550368483526:ios:53f3352a92a2b5a8f09fc7',
    messagingSenderId: '550368483526',
    projectId: 'udemy-flutter-bloc-auth',
    storageBucket: 'udemy-flutter-bloc-auth.appspot.com',
    iosBundleId: 'com.example.fbAuthBloc.RunnerTests',
  );
}
